require("core/options")
require("core/keymaps")
require("core/plugins")
require("core/colorscheme")
require("core/autocmds")
require("plugins/nvim-cmp")
require("plugins/bufferline")
require("plugins/lualine")
